# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterHybirdiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlutterHybirdiOS
  install_all_flutter_pods(flutter_application_path)
  
  target 'FlutterHybirdiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterHybirdiOSUITests' do
    # Pods for testing
  end

end
